//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpa.StoredProcedures.StoredProcedure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HelpaEntities : DbContext
    {
        public HelpaEntities()
            : base("name=HelpaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int GetHelpers(Nullable<int> rADIUS, string lAT, string lONG, System.Data.Entity.Spatial.DbGeography gEO1)
        {
            var rADIUSParameter = rADIUS.HasValue ?
                new ObjectParameter("RADIUS", rADIUS) :
                new ObjectParameter("RADIUS", typeof(int));
    
            var lATParameter = lAT != null ?
                new ObjectParameter("LAT", lAT) :
                new ObjectParameter("LAT", typeof(string));
    
            var lONGParameter = lONG != null ?
                new ObjectParameter("LONG", lONG) :
                new ObjectParameter("LONG", typeof(string));
    
            var gEO1Parameter = gEO1 != null ?
                new ObjectParameter("GEO1", gEO1) :
                new ObjectParameter("GEO1", typeof(System.Data.Entity.Spatial.DbGeography));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetHelpers", rADIUSParameter, lATParameter, lONGParameter, gEO1Parameter);
        }
    }
}
